apiVersion: batch/v1
kind: Job
metadata:
  name: dn-checker
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        app.kubernetes.io/instance: dn-checker
    spec:
      containers:
        - name: alpine
          image: alpine:3.16
          command:
            - entrypoint.sh
          volumeMounts:
            - name: bin
              mountPath: /usr/local/bin
      volumes:
        - name: bin
          configMap:
            name: dn-checker-bin
            defaultMode: 0777
      restartPolicy: OnFailure
