apiVersion: v1
kind: Service
metadata:
  name: app-example
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: app-example
    app.kubernetes.io/instance: app-example
  ports:
    - name: http
      port: 80
      targetPort: http
