apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-example
spec:
  serviceName: app-example
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      app.kubernetes.io/instance: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        app.kubernetes.io/instance: app-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
