apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          env:
            - name: APP_NAME
              value: app-example-success
            - name: DATABASE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: address
