apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-global
spec:
  replicas: 9
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      topology.kubernetes.io/region: global
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        topology.kubernetes.io/region: global
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-us-east-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      topology.kubernetes.io/region: us-east-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        topology.kubernetes.io/region: us-east-1
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-east-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-sa-east-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      topology.kubernetes.io/region: sa-east-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        topology.kubernetes.io/region: sa-east-1
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - sa-east-1
