generatorOptions:
  disableNameSuffixHash: true

namespace: prometheus

resources:
  - alertmanager.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - namespace.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

secretGenerator:
  - name: prometheus-additional-scrape-configs
    files:
      - assets/prometheus.yaml
