apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
            - name: http-healthz
              containerPort: 8080
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates
      volumes:
        - name: nginx-templates
          configMap:
            name: app-example-nginx-templates
