apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-example
spec:
  interval: 5s
  prober:
    url: blackbox-exporter.blackbox-exporter.svc:9115
  targets:
    staticConfig:
      labels:
        service: app-example
      static:
        - http://app-example.app-example.svc:8080/healthz
