version: "3.8"

services:

  app-example-orders:
    image: "node:16.17-alpine"
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - "app-example-orders"
    ports:
      - "3000:3000"
    volumes:
      - "./:/src"
    working_dir: "/src"
    entrypoint: ["npm"]
    command: ["start"]
    environment:
      PORT: "3000"

networks:
  app-example-orders:
    name: "app-example-orders"
