apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
      tolerations:
        - key: foo
          operator: Equal
          value: bar
          effect: NoSchedule
        - key: foo
          operator: Equal
          value: bar
          effect: NoExecute
