apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  config: |

    receivers:
      otlp:
        protocols:
          http:

    exporters:
      logging:
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ logging, jaeger ]
