apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-api-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-api-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-api-exporter
    spec:
      containers:
        - name: json-exporter
          image: quay.io/prometheuscommunity/json-exporter:v0.5.0
          ports:
            - name: http-metrics
              containerPort: 7979
          volumeMounts:
            - name: config
              mountPath: /config.yml
              subPath: config.yml
      volumes:
        - name: config
          configMap:
            name: kube-api-exporter-config
      serviceAccountName: kube-api-exporter
