apiVersion: v1
kind: Service
metadata:
  name: kube-api-exporter
spec:
  selector:
    app.kubernetes.io/name: kube-api-exporter
  ports:
    - name: http-metrics
      port: 7979
      targetPort: http-metrics
