apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      initContainers:
        - name: opentelemetry-install
          image: nginx:1.18
          command: ["opentelemetry-install.sh"]
          volumeMounts:
            - name: opentelemetry-install
              mountPath: /usr/local/bin/opentelemetry-install.sh
              subPath: opentelemetry-install.sh
            - name: opentelemetry-webserver-sdk
              mountPath: /opt/opentelemetry-webserver-sdk
      containers:
        - name: nginx
          image: nginx:1.18
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: opentelemetry-webserver-sdk
              mountPath: /opt/opentelemetry-webserver-sdk
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-templates
              mountPath: /etc/nginx/templates
          env:
            - name: LD_LIBRARY_PATH
              value: /opt/opentelemetry-webserver-sdk/sdk_lib/lib
      volumes:
        - name: opentelemetry-webserver-sdk
          emptyDir: {}
        - name: opentelemetry-install
          configMap:
            name: app-example-opentelemetry-install
            defaultMode: 0777
        - name: nginx
          configMap:
            name: app-example-nginx
        - name: nginx-templates
          configMap:
            name: app-example-nginx-templates
