apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
spec:
  config: |

    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
