services:

  app-traefik:
    image: "traefik:2.9"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.app.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - "80:80"
    networks:
      - "app-traefik"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=app-traefik"
      - "--providers.docker.exposedbydefault=false"

networks:
  app-traefik:
    name: "app-traefik"
